eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8765/eureka
server:
  port: ${random.int(3335,3340)}
  servlet:
    context-path: /microservicio
spring:
  application:
    name: MICROALUMNO
  data:
    mongodb:
      database: alumnoDB
      host: localhost
      port: 27017
