server:
  port: 9095
  servlet:
    context-path: /dominio/ms/afiliado/v1/
spring:
  datasource:
    password: mysecretpassword
    url: jdbc:postgresql://172.17.0.2:5432/postgres
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
