eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: ${PORT:4444}
  servlet:
    context-path: /microservicio
spring:
  data:
    mongodb:
      database: cursoDB
      host: localhost
      port: 27017
